# Nixpacks configuration for Railway
# This ensures all system dependencies are available

[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip", "ffmpeg"]

[phases.install]
cmds = [
  "npm install"
]

[phases.build]
cmds = [
  "pip install --break-system-packages --no-cache-dir torch torchaudio --index-url https://download.pytorch.org/whl/cpu",
  "pip install --break-system-packages --no-cache-dir speechbrain numpy",
  "npm run build"
]

[start]
cmd = "npm start"