# Nixpacks configuration for Railway
# This ensures all system dependencies are available

[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip", "ffmpeg"]

[phases.install]
cmds = [
  "npm install",
  "mkdir -p /opt/python-deps",
  "pip install --break-system-packages --target=/opt/python-deps --index-url https://download.pytorch.org/whl/cpu torch==2.5.0 torchaudio==2.5.0",
  "pip install --break-system-packages --target=/opt/python-deps speechbrain==1.0.3 numpy scipy"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "PYTHONPATH=/opt/python-deps:$PYTHONPATH npm start"