# Nixpacks configuration for Railway
# This ensures all system dependencies are available

[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip", "ffmpeg"]

[phases.install]
cmds = [
  "npm install",
  "pip install --upgrade pip",
  "pip install speechbrain torch torchaudio numpy"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"