name = "ling-zhu"
compatibility_date = "2025-10-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
NODE_ENV = "production"

# Database (if you add Prisma/database integration later)
# DATABASE_URL = "your-database-url"

# Note: For audio processing routes, ensure they are configured as Functions
# Cloudflare Workers have a 30-second CPU time limit on free tier
# Consider using Durable Objects or R2 for longer processing times